language: node_js
node_js: 'lts/*'

addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  yarn: true
  directories:
    - node_modules
    - bower_components
    - .eslintcache
    - $HOME/.cache/bower
    - $HOME/cc

env:
  global:
    - CC_TEST_REPORTER_ID=9798015be3ef64095a2bacb1046d8c981f8bd35e40fda757c431366e786ef566
    - SAUCE_USERNAME=nomego
    - secure: KI7zf2naQz37iqYPDaAKfEM4UCzTHJEE1O2FEFEXktkv0b4DDR8cqqgHLoLscfmyYrsszl9vbyelFU4osspmx5YmOIKeBXzCeKNHvGyWFpr5TViKYC5kIhW2NN8chqrtM243OPey/71VdvAYL8WXs8Hutpe39s0nLuD8NDJ0I0kao1Xsatjd0j4sj1JOkw1Yq+uaqJqEGREnVG0zg5I0TeitDyAh/SCsXLm0k6e1ZasHUSkNMVBNgXNDk2g9INoZCV741h8KL9Rr93jDbJrEusofl0NW3aUGtcxEVaK06Vu2WkUtaFYRYPu8unvqxkCEef/9X6IL7LOc+AM5KxbEEGL8TDlDMasGLD2xNkfAVBYGao2KPLbpGYSWRFfNnWjwBsRzTYspUxTPskwc2A95FuDJcfoVele906+oxjc7k/mUmCBU+gRspVKWyWGZD3IhD0rXdWN8BQu81wLwvP1YUpSV0eQel8Wlij14JlMuE9nDcvl5ABsAn5uLpMwsaiFYpk2rRdYEk6auG5xfrvR3lftloHHoHb69FkzjNBCo4gQGDXyz86EQcFEf8L7KB/r46brBz5Jaio1hQ4p/47eVlNo099a72E6gfF5XNTywPMm4+r4zE7caOEw24B1xzCZbuO8El+OdbTm82aAqkMlsq6/z068VXYNVYsE4u9SyNo8=
    - NEO_CC_URL=https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
    - NEO_CC=$HOME/cc/cc-test-reporter

before_script:
  - yarn lint
  - ([[ -e $NEO_CC ]] || curl -L $NEO_CC_URL > $NEO_CC) && chmod +x $NEO_CC
  - $NEO_CC before-build
script:
  - yarn test $([ -z "$SAUCE_ACCESS_KEY"] && echo "--skip-plugin sauce")
  - $NEO_CC after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  slack:
    secure: kq3rNpziyhKmOF+K5OiA3ekvRdVnlIGd1wtteycfkUMwW7Q5/vkn7K2O56h5aArpaWX6nXLgallXIuy3scW0GHKrJq1vOa7airSI2gSCh7ZEBvqLouM/F+d9Q+fOWX78tdjkIMSJBQbttsBXaURlH6ptcJ8+F59TzPF0kgfbRgtf0KrKY5fYvwOA7yra1EYCWWbjXFVShx6PjnHig48aZtonD9JuMAqlwlgE7TyFbRy9x+jDnMxYTj9cOtTkBZqojO2MgZ/2ew3gf4TPOqkyGRKOt0gXCT9j8I5TRHozUkXD6fWocyVBeUS61brp/2qtXKeEX6NDQS+Jmui67pXX2lMIqO/nypNbnTgqUbYa7TGc0h3kc8le+icRWkeWkY8TO14MZ1TzLd9JacVOqunelWfifOHolMdb14n2kfRwkIT0V70u+DXPW1D6jJfqT4Zkob0uotFpBXGZOetyn/rhRtw9aDwqDkI++eVDHDzWZF7FQGpGNjaXNFTP/bWn8MkD/NxBFL7Z/tO0UaJbVN9YfVoQV+9XGU6Tf6Ls284EJUyXPDpm4bw5dpyJguzEvQ3PXavZ0pP/GaTrD3p9vDFGIyd3h24RTElt4zSuLqJczV6LDnZayGfZmEds1DSUtv2r19V0y1JzHvwgRA43QbVE/mqbllajrSIDPGBxS0bg8Ms=
