language: node_js
node_js: 'lts/*'

addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  yarn: true
  directories:
    - node_modules
    - bower_components
    - .eslintcache
    - $HOME/.cache/bower
    - $HOME/cc

env:
  global:
    - CC_TEST_REPORTER_ID=9798015be3ef64095a2bacb1046d8c981f8bd35e40fda757c431366e786ef566
    - SAUCE_USERNAME=nomego
    - secure: gjwA5OXZqttqb3t11KKEHjaG+jS7ScwzKBpK/uVA9/yL3cAFoWTqOU8vi9g6u0O5Ijj0GmSvxTd+B4v2R9BgaCda4bhznz0DyVtkho4a4MyQmYH3mt+5Ly6eWuxgEOvY6xrpNkL/s0oAl/Ry8mT1/wskvsZUGfPs73gunWl4s9PYkNvRf620FIgxAXEy57fm8CSmsufQljxsIyzhUzMJWOU44/ZUtwoAFw1UxF1EgeqryZhf/fzJ5/HRnkqoRo39+jC0onGf6JOGIu69fZEDxVXI+0mY3ZJ3K7a/Pk7V/zvUR2tx9AWJ4gxG/YpCSXlQgltF4Of4igdIAraSaJmikgn9tMPjWNk6HMDwOt1UiR0yl2gNEI/20Yk4llAFdITA2DFjHRFKodjamD0Q2juwzjZzJw15sF/oAIla6wxvizJYeqB6iRyApcqt5Wt5IrVnHsLPuQI5ATICwnhDmoigg9sOjkA1qHySNelw+Y3EnjiOhfXMcEW13uoFBkK+JMaYTNb/A9o3z0f35f1HyLdzUE52nq2bdSsXd/1gkrBmfbZ3gjyDOwQbjOEudrV1eN6nZdJTVxVoSZcPWTcADSrzzZOEef2w48uV8EBDNBue0yCCbvFyTHjt9FyEF32z0Qbm+AVvI0zUZ+WUWWFDclqby6FQeMKTpP89ew05LvHEMDw=
    - NEO_CC_URL=https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
    - NEO_CC=$HOME/cc/cc-test-reporter
before_script:
  - yarn lint
  - ([[ -e $NEO_CC ]] || curl -L $NEO_CC_URL > $NEO_CC) && chmod +x $NEO_CC
  - $NEO_CC before-build
script:
  - yarn test $([ -z "$SAUCE_ACCESS_KEY"] && echo "--skip-plugin sauce")
  - $NEO_CC after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  slack:
    secure: kq3rNpziyhKmOF+K5OiA3ekvRdVnlIGd1wtteycfkUMwW7Q5/vkn7K2O56h5aArpaWX6nXLgallXIuy3scW0GHKrJq1vOa7airSI2gSCh7ZEBvqLouM/F+d9Q+fOWX78tdjkIMSJBQbttsBXaURlH6ptcJ8+F59TzPF0kgfbRgtf0KrKY5fYvwOA7yra1EYCWWbjXFVShx6PjnHig48aZtonD9JuMAqlwlgE7TyFbRy9x+jDnMxYTj9cOtTkBZqojO2MgZ/2ew3gf4TPOqkyGRKOt0gXCT9j8I5TRHozUkXD6fWocyVBeUS61brp/2qtXKeEX6NDQS+Jmui67pXX2lMIqO/nypNbnTgqUbYa7TGc0h3kc8le+icRWkeWkY8TO14MZ1TzLd9JacVOqunelWfifOHolMdb14n2kfRwkIT0V70u+DXPW1D6jJfqT4Zkob0uotFpBXGZOetyn/rhRtw9aDwqDkI++eVDHDzWZF7FQGpGNjaXNFTP/bWn8MkD/NxBFL7Z/tO0UaJbVN9YfVoQV+9XGU6Tf6Ls284EJUyXPDpm4bw5dpyJguzEvQ3PXavZ0pP/GaTrD3p9vDFGIyd3h24RTElt4zSuLqJczV6LDnZayGfZmEds1DSUtv2r19V0y1JzHvwgRA43QbVE/mqbllajrSIDPGBxS0bg8Ms=
