name: Auto-Approve and Auto-Merge PRs

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  auto-approve-merge-dependabot:
    uses: Neovici/cfg/.github/workflows/automerge.yml@master
    secrets: inherit
